---
- name: "[{{ name }}] Конфигурация конфига"
  block:
    - name: "[{{ name }}] Создаем конфиг"
      vars:
        config_file: "{{ lookup('template', 'nginx.conf.j2') }}"
      community.docker.docker_config:
        name: "{{ name }}.env"
        data: "{{ config_file | b64encode }}"
        labels:
          config: "{{ config_file | hash('sha1') }}"
        data_is_b64: true
        state: present
  tags: "{{ name }}"

  rescue:
    - name: "[{{ name }}] Удаляем сервис"
      community.docker.docker_swarm_service:
        name: "{{ name }}"
        state: absent 

    - name: "[{{ name }}] Создаем конфиг"
      vars:
        config_file: "{{ lookup('template', 'nginx.conf.j2') }}"
      community.docker.docker_config:
        name: "{{ name }}.env"
        data: "{{ config_file | b64encode }}"
        labels:
          config: "{{ config_file | hash('sha1') }}"
        data_is_b64: true
        state: present


  
- name: "[{{ name }}] Выкладка сервиса"
  block:
    - name: "[{{ name }}] Выкладываем сервис"
      community.docker.docker_swarm_service:
        name: "{{ name }}"
        image: "nginx:{{ version }}"
        state: present
        networks:
          - name: "{{ network_name }}"
        publish:
          - mode: ingress
            protocol: tcp
            published_port: 80
            target_port: 80
        configs:
          - config_name: "{{ name }}.env"
            filename: "/etc/nginx/nginx.conf"
  tags: "{{ name }}"