---
- name: "Установка Docker"
  block:
    - name: "Установка дополнительных пакетов"
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - python3-pip
        update-cache: yes
        cache_valid_time: 86400

    - name: "Добавление ключа Docker"
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        keyring: /usr/share/keyrings/docker-archive-keyring.gpg
        state: present

    - name: "Установка стабильного репозитория"
      ansible.builtin.apt_repository:
        repo: >
          deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg]
          https://download.docker.com/linux/ubuntu
          {{ ansible_distribution_release }} stable
        state: present
        update-cache: yes
        filename: docker

    - name: "Установка Docker"
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        update-cache: yes

    - name: "Проверка что докер установлен и перезагружен"
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: "Настройка дополнительных пакетов python"
      block:
        - name: "Установка pip пакетов"
          pip:
            name: docker 

    - name: "Добавление пользователя в группу Docker"
      vars:
        user: andrei
      user:
        name: "{{ user }}"
        groups: docker
        append: yes

  become: true
