---
- name: Создание сети 
  community.docker.docker_network:
    name: "{{ network_name }}"
    driver: overlay

- name: Выкладка сервисов
  vars:
      name: "{{ item.name }}"
      version: "{{ item.version }}"
  include_tasks:
      file: "../services/{{ item.name }}/service.yml"
      apply:
          tags: "{{ item.version }}"
  tags: always
  loop: "{{ services }}"