---
- name: Deploy / build server
  hosts: deploy
  roles:
    - role: preconfig
      tags: preconfig
    - role: build
      tags: build
    - role: deploy
      tags: deploy
    - role: swarm_init
      tags: swarm_init

- name: Managers
  hosts: managers
  roles:
    - role: swarm_join
      tags: swarm_join

- name: Workers
  hosts: workers
  roles:
    - role: swarm_join
      tags: swarm_join


